blank_issues_enabled: false
contact_links:
  - name: Discord Server
    url: https://discord.gg/Wzv2BVQ
    about: Join the tech server this bot was developed for to talk about the project or just to chat in general!
