# Must follow Convention Commits style for action to work properly
# https://www.conventionalcommits.org/en/v1.0.0/

 on:
   push:
     branches:
       - master
 name: release-please
 jobs:
   release-please:
     runs-on: ubuntu-latest
     steps:
       - uses: GoogleCloudPlatform/release-please-action@v3
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           release-type: simple
           # changelog-path: CHANGELOG.md
           package-name: NBC-Boterator
