name: "Close Stale Issues"
on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3.0.12
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been marked stale because it has been open for 30 days with no activity. Remove the stale label or comment on this issue, else it will be closed in 5 days.'
        stale-issue-message: 'This PR has been marked stale because it has been open for 30 days with no activity. Remove the stale label or comment on this PR, else it will be closed in 5 days.'
        close-issue-message: 'Message to post on the stale issue while closing it.' # FIX
        close-pr-message: 'Message to post on the stale pr while closing it.' # FIX
        stale-issue-label: 'status: stale'
        stale-pr-label: 'status: stale'
        exempt-issue-labels: 'XX' # FIX, or just skip?
        exempt-pr-labels: 'XX' # FIX, or just skip?
        days-before-stale: 30
        days-before-close: 5
        # Reference: https://github.com/actions/stale